### ISSUE TITLE
多次导入glide包版本不一致如何兼容

### ISSUE THREAD

**Issue by Mangoxx90** [polyv/polyv-android-livescenes-sdk-demo#1]
主项目使用的glide包版本是3.7.0，保利直播的glide包版本是4.7.1，如何做到既满足主项目需求又满足保利直播需求？或者保利直播是否可以使用低版本glide？

**Comment by SHLURENJIA** [comment]
你好，Glide图片库是Common层内容，我们经过了二次封装。开发者可以自定降低Glide版本适配兼容。可以参考这篇文章：[云课堂Glide 4.x 与 应用Glide 3.x 版本冲突解决方案](https://github.com/polyv/polyv-android-cloudClass-sdk-demo/wiki/%E4%BA%91%E8%AF%BE%E5%A0%82Glide-4.x-%E4%B8%8E-%E5%BA%94%E7%94%A8Glide-3.x-%E7%89%88%E6%9C%AC%E5%86%B2%E7%AA%81%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88)
